import { jsPDF } from 'jspdf';

export const generateItineraryPDF = (itinerary) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed = 10) => {
    if (y + needed > 270) { doc.addPage(); y = 20; }
  };

  // Header bar
  doc.setFillColor(124, 92, 252);
  doc.rect(0, 0, pageW / 2, 14, 'F');
  doc.setFillColor(255, 77, 141);
  doc.rect(pageW / 2, 0, pageW / 2, 14, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('TripTuner ✈', margin, 9);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Powered by Tripi AI', pageW - margin, 9, { align: 'right' });

  y = 26;
  doc.setTextColor(30, 30, 60);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(itinerary.title || 'My India Trip', margin, y);
  y += 8;

  if (itinerary.route) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 160);
    doc.text(itinerary.route, margin, y);
    y += 6;
  }

  doc.setDrawColor(200, 200, 220);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // Stats
  const stats = [
    { label: 'Duration', value: itinerary.duration || '-' },
    { label: 'Group Size', value: itinerary.groupSize ? itinerary.groupSize + ' people' : '-' },
    { label: 'Total Budget', value: itinerary.budgetTotal ? '₹' + Number(itinerary.budgetTotal).toLocaleString('en-IN') : '-' },
    { label: 'Per Person', value: itinerary.budgetPerPerson ? '₹' + Number(itinerary.budgetPerPerson).toLocaleString('en-IN') : '-' },
  ];
  const colW = contentW / stats.length;
  stats.forEach((s, i) => {
    const x = margin + i * colW;
    doc.setFillColor(245, 244, 250);
    doc.roundedRect(x + 1, y, colW - 2, 16, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(120, 120, 160);
    doc.text(s.label, x + colW / 2, y + 5, { align: 'center' });
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 100);
    doc.text(s.value, x + colW / 2, y + 12, { align: 'center' });
  });
  y += 24;

  if (itinerary.plan) {
    itinerary.plan.split('\n').forEach((line) => {
      checkPage(8);
      const t = line.trim();
      if (!t) { y += 3; return; }
      if (/^(DAY|Day )/.test(t)) {
        checkPage(12); y += 2;
        doc.setFillColor(124, 92, 252);
        doc.roundedRect(margin, y - 4, contentW, 10, 2, 2, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(t, margin + 4, y + 3);
        y += 12;
      } else if (t.startsWith('##') || t.startsWith('**')) {
        doc.setTextColor(80, 60, 180);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text(t.replace(/[#*]/g, '').trim(), margin, y);
        y += 7;
      } else if (t.startsWith('-') || t.startsWith('•')) {
        doc.setTextColor(60, 60, 80);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.splitTextToSize('• ' + t.replace(/^[-•]s*/, ''), contentW - 6)
          .forEach(wl => { checkPage(5); doc.text(wl, margin + 4, y); y += 5; });
      } else {
        doc.setTextColor(60, 60, 80);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.splitTextToSize(t, contentW)
          .forEach(wl => { checkPage(5); doc.text(wl, margin, y); y += 5; });
      }
    });
  }

  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFillColor(245, 244, 250);
    doc.rect(0, 285, pageW, 12, 'F');
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 160);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by TripTuner | triptuner.in', margin, 292);
    doc.text('Page ' + i + ' of ' + total, pageW - margin, 292, { align: 'right' });
  }

  const fileName = (itinerary.title || 'trip').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(fileName + '_triptuner.pdf');
};

// Enhanced PDF with better formatting
export const generateEnhancedItineraryPDF = (itinerary) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  const checkPage = (needed = 15) => {
    if (y + needed > pageH - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Header
  doc.setFillColor(124, 92, 252);
  doc.rect(0, 0, pageW, 50, 'F');
  doc.setFontSize(32);
  doc.text(itinerary.emoji || '✈️', margin, 30);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(itinerary.title || 'My India Trip', margin + 20, 25);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(itinerary.route || '', margin + 20, 35);
  doc.setFontSize(10);
  doc.text('Powered by TripTuner & Tripi AI', pageW - margin, 45, { align: 'right' });

  y = 60;

  // Stats
  const stats = [
    { icon: '⏱️', label: 'Duration', value: itinerary.duration || '-' },
    { icon: '👥', label: 'Group', value: itinerary.groupSize || '-' },
    { icon: '💰', label: 'Budget', value: itinerary.budgetTotal?.mid ? `₹${itinerary.budgetTotal.mid.toLocaleString('en-IN')}` : '-' },
    { icon: '💵', label: 'Per Person', value: itinerary.budgetPerPerson?.mid ? `₹${itinerary.budgetPerPerson.mid.toLocaleString('en-IN')}` : '-' },
  ];

  const cardW = (contentW - 12) / 4;
  stats.forEach((stat, i) => {
    const x = margin + i * (cardW + 4);
    doc.setFillColor(245, 244, 250);
    doc.roundedRect(x, y, cardW, 22, 3, 3, 'F');
    doc.setFontSize(16);
    doc.text(stat.icon, x + cardW / 2, y + 8, { align: 'center' });
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 160);
    doc.setFont('helvetica', 'normal');
    doc.text(stat.label, x + cardW / 2, y + 13, { align: 'center' });
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 100);
    doc.setFont('helvetica', 'bold');
    const lines = doc.splitTextToSize(stat.value, cardW - 4);
    doc.text(lines, x + cardW / 2, y + 18, { align: 'center' });
  });

  y += 30;

  // Description
  if (itinerary.description) {
    checkPage(20);
    doc.setFontSize(11);
    doc.setTextColor(80, 60, 180);
    doc.setFont('helvetica', 'bold');
    doc.text('About This Trip', margin, y);
    y += 6;
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 80);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(itinerary.description, contentW);
    doc.text(descLines, margin, y);
    y += descLines.length * 5 + 5;
  }

  // Highlights
  if (itinerary.highlights && itinerary.highlights.length > 0) {
    checkPage(30);
    doc.setFontSize(14);
    doc.setTextColor(124, 92, 252);
    doc.setFont('helvetica', 'bold');
    doc.text('✨ Trip Highlights', margin, y);
    y += 8;

    itinerary.highlights.forEach((highlight) => {
      checkPage(8);
      doc.setFontSize(10);
      doc.setTextColor(255, 77, 141);
      doc.text('●', margin + 3, y);
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 80);
      doc.setFont('helvetica', 'normal');
      doc.text(highlight, margin + 8, y);
      y += 6;
    });
    y += 5;
  }

  // Days
  if (itinerary.days && itinerary.days.length > 0) {
    checkPage(20);
    doc.setFontSize(14);
    doc.setTextColor(124, 92, 252);
    doc.setFont('helvetica', 'bold');
    doc.text('📋 Day-wise Itinerary', margin, y);
    y += 10;

    itinerary.days.forEach((day) => {
      checkPage(40);
      doc.setFillColor(124, 92, 252);
      doc.roundedRect(margin, y, contentW, 10, 3, 3, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`Day ${day.day}: ${day.title}`, margin + 4, y + 7);
      y += 14;

      const activities = [
        { icon: '🌅', time: 'Morning', text: day.morning },
        { icon: '☀️', time: 'Afternoon', text: day.afternoon },
        { icon: '🌆', time: 'Evening', text: day.evening },
        { icon: '🏨', time: 'Stay', text: day.stay },
      ];

      activities.forEach(activity => {
        checkPage(10);
        doc.setFontSize(9);
        doc.setTextColor(124, 92, 252);
        doc.setFont('helvetica', 'bold');
        doc.text(`${activity.icon} ${activity.time}`, margin + 3, y);
        doc.setFontSize(8);
        doc.setTextColor(60, 60, 80);
        doc.setFont('helvetica', 'normal');
        const activityLines = doc.splitTextToSize(activity.text, contentW - 10);
        doc.text(activityLines, margin + 3, y + 5);
        y += 5 + (activityLines.length * 4) + 2;
      });

      y += 4;
    });
  }

  // Budget
  if (itinerary.budgetTotal) {
    checkPage(30);
    doc.setFontSize(14);
    doc.setTextColor(124, 92, 252);
    doc.setFont('helvetica', 'bold');
    doc.text('💰 Budget Breakdown', margin, y);
    y += 10;

    doc.setFillColor(124, 92, 252);
    doc.rect(margin, y, contentW, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    const colW = contentW / 4;
    doc.text('Category', margin + 2, y + 5);
    doc.text('Budget', margin + colW, y + 5);
    doc.text('Mid-Range', margin + colW * 2, y + 5);
    doc.text('Premium', margin + colW * 3, y + 5);
    y += 10;

    const budgetRows = [
      { label: 'Total', budget: itinerary.budgetTotal.budget, mid: itinerary.budgetTotal.mid, premium: itinerary.budgetTotal.premium },
      { label: 'Per Person', budget: itinerary.budgetPerPerson?.budget, mid: itinerary.budgetPerPerson?.mid, premium: itinerary.budgetPerPerson?.premium },
    ];

    budgetRows.forEach((row) => {
      doc.setFillColor(250, 250, 255);
      doc.rect(margin, y, contentW, 7, 'F');
      doc.setTextColor(60, 60, 80);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text(row.label, margin + 2, y + 5);
      doc.setFont('helvetica', 'normal');
      doc.text(row.budget ? `₹${row.budget.toLocaleString('en-IN')}` : '-', margin + colW, y + 5);
      doc.text(row.mid ? `₹${row.mid.toLocaleString('en-IN')}` : '-', margin + colW * 2, y + 5);
      doc.text(row.premium ? `₹${row.premium.toLocaleString('en-IN')}` : '-', margin + colW * 3, y + 5);
      y += 7;
    });
  }

  // Footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(245, 244, 250);
    doc.rect(0, pageH - 12, pageW, 12, 'F');
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 160);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by TripTuner | Powered by Tripi AI', margin, pageH - 6);
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 6, { align: 'right' });
  }

  const fileName = (itinerary.title || 'trip').replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`${fileName}_triptuner_itinerary.pdf`);
};
